###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

$editor = emacsclient -a "" -c
$browser = firefox
$terminal = ghostty

$launcherMenu = noctalia-shell ipc call launcher toggle
$launcherEmoji = noctalia-shell ipc call launcher emoji

$wallpaperPicker = noctalia-shell ipc call wallpaper toggle
$wallpaperRandom = noctalia-shell ipc call wallpaper random Virtual-1
